### PR TITLE
Updated GitHub account switch behaviour for keycutter list

### PR DESCRIPTION
**Pull request by lukeburciu**
The goal of this PR is to reduce the confusion associated with how keycutter prompts during `keycutter list`.

Currently it asks a sometimes confusing question about logging into Github - while already logged in?

This change will now instead ask the user if they wish to sign into another account like so:

**not** switching github.com profiles:
```
$ keycutter list
GitHub CLI: Logged in as lukeburciu.
Do you want to switch to another GitHub account? (Y/n) n
GitHub CLI: Token scopes: 'admin:public_key', 'admin:ssh_signing_key', 'gist', 'read:org', 'repo', 'workflow'
TITLE    ID       KEY     TYPE     ADDED
...SSH key details....
```

switching github.com profiles:
```
$ keycutter list
GitHub CLI: Logged in as lukeburciu.
Do you want to switch to another GitHub account? (Y/n) Y
✓ Logged out of github.com account lukeburciu
? Authenticate Git with your GitHub credentials? Yes

! First copy your one-time code: ABCD-1234
Press Enter to open github.com in your browser...
✓ Authentication complete.
- gh config set -h github.com git_protocol https
✓ Configured git protocol
✓ Logged in as lukeburciu
GitHub CLI: Token scopes: 'admin:public_key', 'admin:ssh_signing_key', 'gist', 'read:org', 'repo', 'workflow'
TITLE    ID       KEY     TYPE     ADDED
...SSH key details....
```

Current behaviour, where it immediately asks to auth to Git w/ github.com credentials
```
$ keycutter list                                                                                                                                                         
? Authenticate Git with your GitHub credentials? Yes

! First copy your one-time code: ABCD-1234
```

### CODE REVIEW

**Comment by mbailey** [comment]
Are you on macOS?

On fedora I see:

```
m@x2 test (master)$ keycutter list
  ✓ Logged in to github.com as mbailey (keyring)
? You're already logged into github.com. Do you want to re-authenticate? (y/N)
```

**Comment by lukeburciu** [comment]
Yep on MacOS Sonoma 14.3.1, running zsh in `iTerm2 Build 3.5.3` and `tmux`

**Comment by mbailey** [comment]
GitHub made a breaking change in ghcli.
Being asked to login each time would be terrible UX.
Your patch addresses this. I need to review it later.

**gh version 2.36.0 (2023-10-04):**

```$ gh auth login \
      --web \
      --git-protocol https \
      --scopes admin:public_key,admin:ssh_signing_key
? You're already logged into github.com. Do you want to re-authenticate? (y/N) ```

**gh version 2.53.0 (2024-07-17):**

```$ gh auth login       --web       --git-protocol https       --scopes admin:public_key,admin:ssh_signing_key

! First copy your one-time code: F181-543C
Press Enter to open github.com in your browser...```

**Comment by mbailey** [comment]
Thanks for your submission. It's solid and well thought out.

**Pull request merged**
